spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog-pro?useUnicode=true&characterEncoding=utf-8
    username: root
    password: ceshiji

logging:
  level: info
  file: log/blog-pro.log